module.exports = {


    board_env: "STM32F103RE_creality",
    active: true,
    only: "stable",   // build only stable branch
    meta: {
        stable_name: "ender3pro_v4.2.2_M{{marlin_version}}-custom-{{current_date}}",
        nightly_name: "ender3pro_v4.2.2_{{current_date}}-custom-{{uid}}"
    },


    based_on: {   // default Ender-3 Pro Marlin example config
        repo: "https://github.com/MarlinFirmware/Configurations/",
        path: "/config/examples/Creality/Ender-3 Pro/CrealityV422/",
        stable_branch: "release-2.1.2",   // latest stable
        nightly_branch: "bugfix-2.1.x"    // latest nightly
//        repo: "https://github.com/zisismaras/ender_3_4.2.2_firmware",
//        path: "/autogeneratedConfigs/baseLin/{{releaseType}}/latest",  // {{releaseType}} will be either stable or nightly
//        stable_branch: "master",
//        nightly_branch: "master"
    },


    configuration:     {   // "Configuration.h" customizations
        enable: [

            ["STRING_CONFIG_H_AUTHOR", "(Dust, valerionew, Ender-3, zisismaras, KamensekD)"],

            //standard leveling menu helper
            "LCD_BED_TRAMMING",
            "BED_TRAMMING_INCLUDE_CENTER"

            //PLA Preheat Constants
            ["PREHEAT_1_TEMP_HOTEND", 180],
            ["PREHEAT_1_TEMP_BED", 50],
            //ABS Preheat Constants
            ["PREHEAT_2_TEMP_HOTEND", 225],
            ["PREHEAT_2_TEMP_BED", 50]

        ]
    },


    configuration_adv: {   // "Configuration_adv.h" customizations
        enable: [

            //octoprint
            "HOST_ACTION_COMMANDS"

        ]
    }


};
