module.exports = {

    board_env: "STM32F103RE_creality",
    //active: false,
    //only: "stable",   // build only stable branch
    meta: {
        stable_name: "ender3pro_v4.2.2_M{{marlin_version}}-custom-{{current_date}}",
        nightly_name: "ender3pro_v4.2.2_{{current_date}}-custom-{{uid}}"
    },

    based_on: {   // default Ender-3 Pro Marlin example config
        repo: "https://github.com/MarlinFirmware/Configurations/",
        path: "/config/examples/Creality/Ender-3 Pro/CrealityV422/",
        stable_branch: "release-2.1.2",   // latest stable
        nightly_branch: "bugfix-2.1.x"    // latest nightly
//        repo: "https://github.com/zisismaras/ender_3_4.2.2_firmware",
//        path: "/autogeneratedConfigs/baseLin/{{releaseType}}/latest",  // {{releaseType}} will be either stable or nightly
//        stable_branch: "master",
//        nightly_branch: "master"
    },

    
                           // refer to:   https://github.com/zisismaras/marlin_auto_build
                           // for valid syntax
    configuration:     {   // "Configuration.h" customizations
        enable: [

            
            
            ["STRING_CONFIG_H_AUTHOR", "(Dust, valerionew, Ender-3, zisismaras, KamensekD)"],
            ["CUSTOM_MACHINE_NAME",  q`Ender-3 Pro V1.5 4.2.2`],

            
            //Standard leveling menu helper
            "LCD_BED_TRAMMING",
            "BED_TRAMMING_INCLUDE_CENTER",

            
            //Stepper Driver Types
            //"Creality 4.2.2 boards come with a variety of stepper drivers.
            //Check the board label (typically on SD Card module) and set the correct *_DRIVER_TYPE!
            //(C=HR4988, E=A4988, A=TMC2208, B=TMC2209, H=TMC2225, H8=HR4988)
            //* Use TMC2208/TMC2208_STANDALONE for TMC2225 drivers and TMC2209/TMC2209_STANDALONE for TMC2226 drivers.
            //* Options: A4988, A5984, DRV8825, LV8729, TB6560, TB6600, TMC2100,
            //*          TMC2130, TMC2130_STANDALONE, TMC2160, TMC2160_STANDALONE,
            //*          TMC2208, TMC2208_STANDALONE, TMC2209, TMC2209_STANDALONE,
            //*          TMC26X,  TMC26X_STANDALONE,  TMC2660, TMC2660_STANDALONE,
            //*          TMC5130, TMC5130_STANDALONE, TMC5160, TMC5160_STANDALONE
            ["X_DRIVER_TYPE",  q`A4988`],
            ["Y_DRIVER_TYPE",  q`A4988`],
            ["Z_DRIVER_TYPE",  q`A4988`],
            ["E0_DRIVER_TYPE", q`A4988`],
            
            
            //Preheat Constants
            ["PREHEAT_1_LABEL", "PLA"],
            ["PREHEAT_1_TEMP_HOTEND", 200],
            ["PREHEAT_1_TEMP_BED", 50],
            
            ["PREHEAT_2_LABEL", "PETG"],
            ["PREHEAT_2_TEMP_HOTEND", 225],
            ["PREHEAT_2_TEMP_BED", 50],
 
            
            //Enable Linear Advance and set default K to 0
            "LIN_ADVANCE",
            ["LIN_ADVANCE_K", 0],
            "EXPERIMENTAL_SCURVE",
            "ALLOW_LOW_EJERK",

            
            //Auto Level
            ["GRID_MAX_POINTS_X", 5],
            "BLTOUCH",
            "AUTO_BED_LEVELING_BILINEAR",
            "Z_SAFE_HOMING",
            "USE_PROBE_FOR_Z_HOMING",
            ["Z_MIN_PROBE_PIN", q`PB1`],
            "LCD_BED_LEVELING",

            ["DEFAULT_LEVELING_FADE_HEIGHT", 40],
            ["NOZZLE_TO_PROBE_OFFSET", [-27, 0, 0]],
            // my printer's probe offsets: M851 X-27.00 Y0.00 Z-1.50 ; (mm)

            //M48 test
            "Z_MIN_PROBE_REPEATABILITY_TEST",

        
        ],
        disable: [
            "Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN",

            
        ]
    },

    

    configuration_adv: {   // "Configuration_adv.h" customizations
        enable: [
           
            
            //octoprint
            "HOST_ACTION_COMMANDS",

            // for Auto Level
            "BABYSTEPPING",
            "BABYSTEP_ZPROBE_OFFSET",
            "PROBE_OFFSET_WIZARD",

            //symmetrical
            ["PROBING_MARGIN_LEFT", 20],
            ["PROBING_MARGIN_RIGHT", 20],
            ["PROBING_MARGIN_FRONT", 10],
            ["PROBING_MARGIN_BACK", 10],
        
            
        ]
    }

    

};
