module.exports = {
    board_env: "STM32F103RE_creality",
    active: false,
    only: "stable",
    meta: {
//        stable_name: "ender3pro_v4.2.2-2.1.2-kamac-{{uid}}",
//        nightly_name: "ender3pro_v4.2.2-{{current_date}}-kamac-{{uid}}"
// //        stable_name: "ender3_v4.2.2-2.1.2-kamac-{{uid}}",
// //        nightly_name: "ender3_v4.2.2-{{current_date}}-kamac-{{uid}}"
        stable_name: "ender_3_v4.2.2-{{marlin_version}}-base-{{uid}}",
        nightly_name: "ender_3_v4.2.2-{{current_date}}-base-{{uid}}"

    },
    based_on: {
        repo: "https://github.com/zisismaras/ender_3_4.2.2_firmware",
        path: "/autogeneratedConfigs/baseLin/{{releaseType}}/latest",  // {{releaseType}} will be either stable or nightly
        stable_branch: "master",
        nightly_branch: "master"

//        repo: "https://github.com/MarlinFirmware/Configurations/",
//        path: "/config/examples/Creality/Ender-3 Pro/CrealityV422/",
//        stable_branch: "release-2.1.2",
//        nightly_branch: "bugfix-2.1.x"

// //        repo: "https://github.com/MarlinFirmware/Configurations/",
// //        path: "/config/examples/Creality/Ender-3/CrealityV422/",
// //        stable_branch: "release-2.1.2",
// //        nightly_branch: "bugfix-2.1.x"

    },
        configuration: {
        enable: [
            //PLA Preheat Constants
            ["PREHEAT_1_TEMP_HOTEND", 180],
            ["PREHEAT_1_TEMP_BED", 50],
            ["STRING_CONFIG_H_AUTHOR", "(Dust, valerionew, Ender-3, zisismaras)"],
            //standard leveling menu helper
            "LCD_BED_TRAMMING",
            "BED_TRAMMING_INCLUDE_CENTER"
        ]
    },
    configuration_adv: {
        enable: [
            //octoprint
            "HOST_ACTION_COMMANDS"
        ]
    }
};
